"""FastAPI application exposing an OpenAI-compatible API for DeepSeek.

The HTTP surface (``/v1/chat/completions`` and ``/v1/models``) is generated by
``fastapi-openai-compat``. All DeepSeek-specific logic lives in
``deepseek_harness.provider``.
"""

from __future__ import annotations

from fastapi_offline import FastAPIOffline
from fastapi.middleware.cors import CORSMiddleware
from fastapi_openai_compat import create_chat_completion_router

from .provider import list_models, run_completion

app = FastAPIOffline()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

router = create_chat_completion_router(
    list_models=list_models,
    run_completion=run_completion,
    owned_by="deepseek",
)
app.include_router(router)


@app.get("/")
async def root() -> dict:
    return {"status": "ok", "message": "DeepSeek API Proxy is running"}


@app.get("/health")
async def health() -> dict:
    return {"status": "healthy"}